Feature/sling 9057 update javax activation
apache/sling-org-apache-sling-javax-activation pull request #1
Opened 2020-02-07 11:45 UTC by ugocei

2020-02-07 15:14 UTC, kwin requested changes

2020-02-07 15:14 UTC, kwin commented on pom.xml
> +        <javax.activation.version>1.2.0</javax.activation.version>
1.2.1 is the newest version with a better license (EDL)

2020-02-07 15:14 UTC, kwin commented on pom.xml
> +            <groupId>com.sun.activation</groupId>
the newest version is available from https://search.maven.org/artifact/com.sun.activation/jakarta.activation/1.2.1/jar.

2020-02-10 07:17 UTC, kwin approved these changes
LGTM now. We must not forget to remove the additional notice and license file from https://github.com/apache/sling-org-apache-sling-javax-activation/tree/master/src/main/appended-resources/META-INF.

2020-07-24 09:54 UTC, bosschaert commented
This is a fairly old PR at this stage, but I see that @kwin requested additional changes:

@kwin wrote:
> We must not forget to remove the additional notice and license file from https://github.com/apache/sling-org-apache-sling-javax-activation/tree/master/src/main/appended-resources/META-INF.

@ugocei would you have time to update the branch with these changes?

2020-07-24 12:12 UTC, kwin commented
1.2.2 is available meanwhile...

2020-07-24 18:22 UTC, kwin commented
I will pick this up next week.

2020-07-25 13:17 UTC, closed without merging